# Generated by Django 5.2.14 on 2026-06-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('project_view', 'Project View'), ('blog_view', 'Blog View'), ('resume_download', 'Resume Download'), ('contact_submit', 'Contact Submit')], max_length=50)),
                ('object_id', models.CharField(blank=True, help_text='UUID of project or post', max_length=100)),
                ('object_title', models.CharField(blank=True, help_text='Snapshot of title', max_length=300)),
                ('session_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='analytics_e_event_t_acfd0a_idx'), models.Index(fields=['-created_at'], name='analytics_e_created_659b3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('session_key', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_pageview',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path'], name='analytics_p_path_3382b5_idx'), models.Index(fields=['-created_at'], name='analytics_p_created_44ec6b_idx'), models.Index(fields=['session_key'], name='analytics_p_session_1f2553_idx')],
            },
        ),
    ]
