# Generated by Django 5.2.14 on 2026-06-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Kevin Manoti', max_length=200)),
                ('tagline', models.CharField(default='Full Stack Engineer', help_text='Short role/title shown in the hero', max_length=300)),
                ('bio_short', models.CharField(blank=True, help_text='One-liner shown in hero sub-tagline', max_length=500)),
                ('bio_long', models.TextField(blank=True, help_text='Full bio shown in the About section (supports line breaks)')),
                ('bio_long_2', models.TextField(blank=True, help_text='Second paragraph of bio (optional)')),
                ('location', models.CharField(default='Nairobi, Kenya', max_length=200)),
                ('open_to_work', models.BooleanField(default=True, help_text="Controls the 'Available for opportunities' badge")),
                ('availability_text', models.CharField(default='Available for opportunities', max_length=200)),
                ('email', models.EmailField(blank=True, default='kevin@kevinmanoti.dev', max_length=254)),
                ('github_url', models.URLField(blank=True, default='https://github.com/kevinmanoti')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/kevinmanoti')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/kevinmanoti')),
                ('website_url', models.URLField(blank=True)),
                ('stat_experience', models.CharField(default='5+', help_text='e.g. 5+', max_length=20)),
                ('stat_projects', models.CharField(default='30+', help_text='e.g. 30+', max_length=20)),
                ('stat_technologies', models.CharField(default='20+', help_text='e.g. 20+', max_length=20)),
                ('stat_open_source', models.CharField(default='50+', help_text='e.g. 50+', max_length=20)),
                ('meta_description', models.CharField(blank=True, default='Full Stack Engineer specialising in Django, React, and PostgreSQL.', max_length=300)),
                ('profile_image', models.ImageField(blank=True, help_text='Used in the About section card', null=True, upload_to='profile/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'db_table': 'core_sitesettings',
            },
        ),
    ]
