# Generated by Django 5.2.14 on 2026-06-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='github_username',
            field=models.CharField(blank=True, default='kevinmanoti', help_text='GitHub username for repository import feature', max_length=100),
        ),
    ]
