# Generated by Django 6.0.4 on 2026-06-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('full_stack', 'Full Stack'), ('data_engineering', 'Data Engineering')], db_index=True, default='full_stack', max_length=30),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category'], name='portfolio_p_categor_f3435c_idx'),
        ),
    ]
