# Generated by Django 5.2.14 on 2026-06-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_category_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_repo_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='GitHub repository ID — set on import, prevents duplicates', null=True, unique=True),
        ),
    ]
